name: 'multiple_datasets'
sessions: 
  - name: 'two_fingers'
    file: '/oak/stanford/groups/henderj/nishalps/gesture/t5.2021.11.01/data_15ms/'
    time_steps_before_movement: 33
    time_steps_after_movement: 30
  - name: 'two_fingers'
    file: '/oak/stanford/groups/henderj/nishalps/gesture/t5.2021.10.25/data_15ms/'
    time_steps_before_movement: 33
    time_steps_after_movement: 30
    num_fingers_moving: [0, 1]